Repository 3x071c/lsg, pull requests merged in 2022-03, with the labels that each got.

#134 ci: remove renovate limit
  .github/renovate.json
Labels: in progress

#136 ci: fix renovate grouping
  .github/renovate.json
Labels: in progress

#46 feat: added page (create, edit, delete) mutations
  .github/renovate.json
  .vscode/launch.json
  db/seed.ts
  graphql/schema/Page.ts
  graphql/schema/User.ts
  pages/api/index.ts
  pnpm-lock.yaml
Labels: ready for review

#144 chore: renamed repository
  README.md
  package.json
Labels: in progress

#145 chore: merge renovate via kodiak
  .github/.kodiak.toml
  .github/renovate.json
Labels: in progress

#146 fix: remix app server
  .vscode/settings.json
  package-lock.json
  package.json
  remix.config.js
  server.js
  vercel.json
Labels: in progress

#147 docs: updated docs, refactored scripts
  README.md
  package.json
Labels: in progress

#148 ci: fixed build script
  package-lock.json
  package.json
  remix.config.js
Labels: in progress

#149 feat: integrate mysql
  .husky/commit-msg
  .husky/pre-commit
  README.md
  app/routes/index.tsx
  db/schema.prisma
  package.json
Labels: in progress

#150 feat: use swc for ts-node transpilation
  .cspell.json
  .eslintignore
  .gitignore
  .jscpd.json
  .prettierignore
  .secretlintignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  tsconfig.json
Labels: in progress

#153 feat: performance optimization
  app/colormode/ColorModeManager.tsx
  app/colormode/getColorMode.ts
  app/entry.client.tsx
  app/entry.server.tsx
  app/hooks/index.ts
  app/hooks/remount/RemountContext.tsx
  app/hooks/remount/RemountProvider.tsx
  app/hooks/remount/index.ts
  app/hooks/remount/useOnRemount.tsx
  app/root.tsx
Labels: in progress

#157 feat: homepage navbar
  .cspell.json
  README.md
  app/hero/Hero.tsx
  app/links/LinkButton.tsx
  app/nav/Navbar.tsx
  app/nav/index.ts
  app/routes/index.tsx
  db/data/Beratung/Mittelstufe.md
  db/data/Beratung/Nachhilfe.md
  db/data/Beratung/Oberstufe.md
  db/data/Beratung/Schulberatung.md
  db/data/Beratung/Schulpsychologie.md
  db/data/Beratung/Unterstufe.md
  db/data/Informationen/Eltern.md
  db/data/Informationen/Lehrkräfte.md
  db/data/Informationen/Schüler.md
  db/data/Profile/EVA.md
  db/data/Profile/Fremdsprachen.md
  db/data/Profile/Informationstechnik.md
  db/data/Profile/Kunst.md
  db/data/Profile/MINT.md
  db/data/Profile/Musik.md
  db/data/Profile/Schulsanitätsdienst.md
  db/data/Profile/Schülerzeitung.md
  db/data/Profile/Sport.md
  db/data/Profile/Theater.md
  db/data/Schule/Ausbildungsrichtungen.md
  db/data/Schule/Erziehungspartnerschaft.md
  db/data/Schule/Kontakt.md
  db/data/Schule/Leitbild.md
  db/data/Schule/Mensa.md
  db/data/Schule/Schulentwicklungsplan.md
  db/data/Schule/Strukturdaten.md
  db/data/Schulfamilie/Elternbeirat.md
  db/data/Schulfamilie/Förderverein.md
  db/data/Schulfamilie/Schulleitung.md
  db/data/Schulfamilie/Verwaltung.md
  db/migrations/20220316223827_add_page_categories/migration.sql
  db/migrations/20220317175139_remove_user_model/migration.sql
  db/schema.prisma
  db/seed.ts
  package-lock.json
  package.json
Labels: ready for review

#159 refactor: clean up
  app/CatchBoundary.tsx
  app/ErrorBoundary.tsx
  app/colormode/colorModeCookie.ts
  app/entry.client.tsx
  app/entry.server.tsx
  app/hero/Hero.tsx
  app/hooks/index.ts
  app/layout/Container.tsx
  app/layout/index.ts
  app/layout/useBreakpoints.ts
  app/nav/Navbar.tsx
  app/remount/RemountContext.tsx
  app/remount/RemountProvider.tsx
  app/remount/index.ts
  app/remount/useOnRemount.tsx
  app/root.tsx
  app/routes/index.tsx
  app/util/index.ts
  app/util/parseCookie.ts
  db/seed.ts
Labels: in progress

#162 chore: increment Node.js version to latest LTS (16) as minimum supported
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: in progress

#164 feat: auth
  .eslintrc.js
  README.md
  app/CatchBoundary.tsx
  app/ErrorBoundary.tsx
  app/auth/index.ts
  app/auth/passwords.server.ts
  app/auth/session.server.ts
  app/colormode/ColorModeContext.tsx
  app/colormode/ColorModeManager.tsx
  app/colormode/InitialColorModeContext.tsx
  app/colormode/index.ts
  app/colormode/setColorMode.ts
  app/colormode/useColorModeCookie.tsx
  app/colormode/useInitialColorModeCookie.tsx
  app/entry.server.tsx
  app/form/FormInput.tsx
  app/form/SubmitButton.tsx
  app/form/index.ts
  app/links/isExternal.ts
  app/prisma/index.ts
  app/prisma/provider.server.ts
  app/remount/RemountProvider.tsx
  app/remount/index.ts
  app/root.tsx
  app/routes/cms/index.tsx
  app/routes/cms/login.tsx
  app/routes/index.tsx
  db/migrations/20220320205502_add_user_model/migration.sql
  db/schema.prisma
  db/seed.ts
  package-lock.json
  package.json
Labels: in review

#170 fix: deployment
  package.json
Labels: in progress

#171 feat: cms nav
  app/cms/Nav.tsx
  app/cms/index.ts
  app/routes/admin/cms/index.tsx
  app/routes/admin/login.tsx
Labels: in review
